### ISSUE TITLE
Whyyyyyy we have duplicate effort like this? ;-(

### ISSUE THREAD

**Issue by pfalcon** [darius/tailbiter#1]
I can't believe this happening to me, and to us as a community. Short summary: ~1month ago I got an idea that it totally won't do to have Python compilers written in C, like CPython and MicroPython projects do, and there should be unbloated and easily hackable compiler written in Python. (Unbloated and hackable is a must, everyone looked into PyPy to not understand/reuse much.)

A week later, after gazillion of googling and reviewing ~100 projects on github (I know because I cloned each of them), I figured the best candidate would be Python2's "compiler" package from stdlib. That's already a chunk of irony - I use Python since 1.5.1 times, and never knew it had such. So it's quite ironical that I spent a week looking for something which was before my nose (in the docs) for many years - but then again ironized by the fact that they cowardly abandoned it for Python3.

So, over last 3 weeks, I daily (mostly nightly) worked on forward-porting Python2's "compiler" to Python3 syntax and AST: https://github.com/pfalcon/python-compiler

Finally, after spending all this weekend, I finally got to a milestone that only 5 files from Python3.4 stdlib fail to compiler correctly (or exactly). And righ this moment, googling up something barely related and minor, I found your blog post https://codewords.recurse.com/issues/seven/dragon-taming-with-tailbiter-a-bytecode-compiler and these projects (this one and https://github.com/darius/500lines).

Why, or why? Python2's compiler isn't the cleanest code (it has Python1 legacy), who knows, I might have been better off starting with your code. Before I'm going to find that out, I wanted to make this interjection...

**Comment by darius** [comment]
Hello! I'm sorry about letting this project fall into such obscurity. I got neurotic about my writing in the article you linked to.

Now that you've done all that work you probably won't want to ditch it -- I'd feel the same way. Maybe you'll find some ideas here to help streamline your full compiler's code, though -- e.g. http://abecedarius.tumblr.com/post/77679122389/ouroborospy (a comparison from an early draft of Tailbiter). You already have most of a complete compiler, while mine is for a pretty small subset of the language.

If you haven't seen it already, http://www.oilshell.org/blog/tags.html?tag=opy#opy is also of interest.

**Comment by pfalcon** [comment]
Thanks for reply, and a quick one! I now seem to have connected pieces together - reading https://codewords.recurse.com/issues/seven/dragon-taming-with-tailbiter-a-bytecode-compiler I couldn't shake the feeling that it would have been a great contribution for the "500 lines" book, and at the end, it said it was intended to!

Really a pity it didn't fit in :-(. If they will run 2nd edition, pleasy-please try to push it in ;-).

So I now see that https://github.com/darius/500lines/tree/master/bytecode-compiler is a version of the tailbiter for the book. So yes, I didn't waste effort, as being able to compile large corpus of real Python code, not just a subset, requires dealing with a lot of details. 

But tailbiter is definitely what I was looking for a month ago, at least as a motivation - a simple and small Python AST to bytecode compiler, something similar to the proverbial "pyvm2 by Paul
Swartz (z3p), from http://www.twistedmatrix.com/users/z3p/". That link is dead now and I don't know how many people saw the original pyvm2 code, but it lives on (in largely unencumbered form!) in the Byterun project.

All in all, specific suggestions on how to improve the situation:

1. Can you please add "python-compiler" tag on the project here on github to join small list of https://github.com/topics/python-compiler
2. Better github project description would help. "just enough Python to Python in Python" is absolutely not searchable. Something like "Python bytecode compiler from grounds up" would be much better.

Thanks in advance!

**Comment by darius** [comment]
Done, thanks for the suggestions.
